rm -v objs/core/Pulay.o
rm -v objs/electronic/BandDavidson.o
rm -v objs/electronic/BandMinimizer.o
rm -v objs/electronic/ElecMinimizer.o
rm -v objs/electronic/IonicMinimizer.o
rm -v objs/electronic/RadialSchrodinger.o
rm -v objs/fluid/FluidMixture.o
rm -v objs/fluid/LinearPCM.o
rm -v objs/fluid/NonlinearPCM.o
rm -v objs/fluid/SaLSA.o
rm -v objs/wannier/WannierMinimizer.o
