/*-------------------------------------------------------------------
Copyright 2011 Ravishankar Sundararaman

This file is part of JDFTx.

JDFTx is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

JDFTx is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with JDFTx.  If not, see <http://www.gnu.org/licenses/>.
-------------------------------------------------------------------*/

#ifndef JDFTX_CONFIG_H
#define JDFTX_CONFIG_H

//Configuration definitions processed by Cmake
//	Do not edit config.h, it is generated by Cmake
//	Edit config.in.h instead

#define PACKAGE_NAME "JDFTx"
#define PACKAGE_DESCRIPTION "The playground for joint density functional theory"
#define PACKAGE_SUMMARY "Toolkit for rapid development of density-functional methods"
#define VERSION_MAJOR_MINOR_PATCH "1.4.2"
#define VERSION_HASH ""
#define JDFTX_BUILD_DIR "/home/efefer/WORKS/JDFTX/jdftx-1.4.2/build"

#endif // JDFTX_CONFIG_H
